[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aorus-assistant"
version = "0.1.0"
description = "Aorus Assistant 專案"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]

dependencies = [
    # "requests>=2.31.0",
    "llama-cpp-python>=0.3.36",
    "sentence-transformers>=6.1.0",
]

# [project.scripts]
# aorus-cli = "aorus_assistant.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/aorus_assistant"]
